html5/connect.html
Before the fix, selecting the radioboxes nor specifying the command
to run had no effect. Now selecting 'Start' and 'Start Desktop' works
with or without the command specified.
=> Fix assignment of 'action' and 'start' params

html5/js/Client.js
Fixes the logic flaw spawning new and new displays on reconnection
if "start" / "start-desktop" is invoked.
=> Drop start-new-session after first time connection

html5/js/Client.js
Fixes second/third/fourth attempt to reconnect caused by zero as last_echo_ping.
=> Do not emit connection-lost immediately after successful reconnect

docs/Configuration.md, html5/connect.html, html5/index.html
Summary of changes:
﻿  * Add and document `override_width` in pixels
* Adjust viewport scaling if width is overridden
* Add meta tags for fullscreen operation on iOS and
Android when user adds the Xpra HTML5 client webpage
to home screen.
=> Implement override of client screen width

html5/index.html
Fixes reconnects triggered by 'connection-lost' after user
requested the remote Xpra server to shut down.
=> Close client if user confirmed server shutdown

html5/js/Keycodes.js, html5/js/Utilities.js
Also fix Ukrainian X11 layput name override, so browser-supplied
language 'uk' is consistently mapped to X11's 'ua' layout, making
xkbcomp happy.
=> Fix broken language-to-keymap matcher

html5/css/client.css
This is the current looking of a window with Xpra-html client:
Most desktop environment nowadays uses round corners, for example:
MacOS
Linux XFCE
This PR will make the window looks like this:
=> Make window corners round

setup.py
The default-settings.txt file is a configuration file
editable by user, so its place on Unix systems is
in /etc.
Also fix typo in make_rpm
=> Move default-settings to /etc/xpra

html5/js/DecodeWorker.js
decode_rgb returns a ArrayBuffer instead of Uint8Array. This causes an error (ImageData byte length is not a multiple of 4 * width) on line 185 if no re-striding is done.
=> return Uint8Array if no re-striding is needed

html5/index.html, html5/js/Client.js
This fixes a bug where the clipboard was getting overwritten by server-side copies, even when `clipboard_direction=to-server`. This prevents server-side copies when `clipboard_direction=to-server`.
One must set `clipboard_direction` in `default_settings.txt` to use this fix.
Note: We don't need to send the clipboard on every keyboard event. Capturing the contents on focus should be sufficient, if the intent is to copy data from the client browser to the server.
Credit: @danisla
=> Fix clipboard-related event handlers

html5/index.html, html5/js/Client.js
This fixes a bug where, if the user defocused Xpra shortly after pressing a key (sending a keydown), that key could get stuck (the matching keyup would never be sent).
=> Prevent stuck keys (by sending keyup on blur)

html5/css/menu-skin.css, html5/css/slick.css, html5/index.html, html5/js/Client.js, html5/js/lib/slick.js
After pressing `Alt+Tab` but before releasing `Alt`, a semi-transparent popup visualizes the window stack and previews the next windows that each additional `Tab` press would select. Meanwhile, each real window change is instantly performed behind the popup.
Idea & implementation credit: @danisla
=> Preview windows when alt-tabbing

html5/js/Client.js
auto-fullscreen was being evaluated in the request_redraw handler to cover cases where resizing the browser window would break the target auto-fullscreen window.
Moved this functionality into the client _screen_resized handler instead.
Working as expected in my tests.
=> move the auto-fullscreen feature out of request_redraw

html5/index.html, html5/js/Client.js
I added keycloak authentication as discussed.
Unsure how to display the error messages in the client when the authentication failed in the function check.
Please check this PR together with the PR in [xpra](https://github.com/Xpra-org/xpra/pull/3486). Let me know if anything needs to be improved.
=> Added keycloak authentication

docs/Configuration.md, html5/connect.html, html5/index.html, html5/js/Client.js
The `scroll_reverse_y` setting incorrectly handled MacOS natural scrolling. This solution should properly detect vertical scrolling inversion at runtime.
See https://deepmikoto.com/coding/1--javascript-detect-mouse-wheel-direction for the auto-detection approach.
=> Replace `scroll_reverse_y` setting with auto-detection

.github/workflows/ci.yml
In using this one-job workflow, I noticed that the names of the workflow & job are not very descriptive or accurate.
---
What do you think of these new names?
=> Rename GitHub Actions workflow & job for accuracy

html5/js/Utilities.js
`typeof` can return `"undefined"` but not `undefined`. The current implementation is certainly not intentional, but I don't know if this fix will cause any bugs.
=> Fix comparison value stringiness

.eslintrc.js, .github/workflows/ci.yml, html5/index.html, html5/js/Client.js, html5/js/DecodeWorker.js, html5/js/OffscreenDecodeWorker.js, html5/js/Protocol.js, html5/js/Utilities.js, html5/sw.js, package-lock.json, package.json
This finds ECMAScript antipatterns (both syntactical and logical) and suggests fixes. I find that codebases with a linter have fewer bugs and reduced cognitive load, in both reading and writing!
As with the formatter, I've added a parallel CI job for the linter to give a green light.
=> Add ESLint-based linting via npm

.gitignore, html5/connect.html, html5/css/simple-keyboard.css, html5/index.html, html5/js/Client.js, html5/js/DecodeWorker.js, html5/js/Keycodes.js, html5/js/MediaSourceUtil.js, html5/js/Menu-custom.js, html5/js/Notifications.js, html5/js/Protocol.js, html5/js/RgbHelpers.js, html5/js/Utilities.js, html5/js/Window.js, setup.py
I don't know which of these lines were commented-out temporarily, accidentally, or for documentation. Regardless, commented-out code presents unnecessary cognitive load during onboarding, development, and maintenance. Therefore, we should remove non-documentation comments and visually distinguish permanent documentation comments from simply-temporary/accidental `//` insertions. Please let me know if any of these comment deletions go too far!
=> Remove all commented-out code

html5/js/Client.js
According to the readme, the client is compatible "with any currently supported version". Xpra 3.1.x is still listed as supported. Hence, I assume it's a bug.
The PR is against the 5.x branch, since master is completely broken with Xpra 3.1.x due to the switch to rencodeplus. Not sure if it's intended.
The bug is present in the 4.x branch as well, but no idea if this branch is still supported. If it is, please consider backporting to 4.x.
=> fix windows movement with Xpra 3.1.x

html5/js/Utilities.js
This fixes a decoding issue when copying UTF-8 characters (that are not ASCII) from the web-client to the host by using the built-in text encoding/decoding functionality ([TextDecoder](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder), [TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder)).
As a result, the code is significantly easier to read and understand, however this does break compatibility with IE.
=> Use TextEncoder/TextDecoder to handle string conversion to/from UTF-8

html5/js/Client.js, html5/js/Protocol.js, html5/js/Utilities.js, html5/js/lib/rencode.js
Fixes the encoding issue when using authentication by using Uint8ToString from `rencode.js` in the `_process_challenge`-function. Also started removing legacy encoding.
We have to test this thoroughly before merging, as it may have unintended effects that I have yet to discover.
Fixes #260
=> Fix encoding issue when using authentication.

html5/js/Client.js, html5/js/Window.js
Should improve the consistency of window positioning when a window includes the "fullscreen" metadata. 
- Prevents applying an offset position for a fullscreen window positioned at (0, 0)
- Prevents a fullscreen window from being treated as resizable and thus receiving window decorations (and a subsequent topoffset).
=> More consistent positioning of fullscreen windows

html5/connect.html, html5/index.html, html5/js/Utilities.js
In case of multiple xpra sessions behind a single domain (i.e. reverse proxy), the sessions will overwrite their settings inside the sessionStorage when the user navigates between the sessions within a browser tab. This change will store the sessionStorage data prefixed with the pathname of the xpra session. This fixes #278
=> Bugfix: Prefix the sessionStorage data with pathname

README.md
Reverts Xpra-org/xpra-html5#280
This isn't needed anyway.
=> Don't use Debian specific commands in the generic README

html5/js/Utilities.js
URL parameters are not being applied in connect.html or index.html. The root cause is that the `getparam()` function in Utitiles is effectively ignoring url parameters.
=> Bugfix URL parameters not being applied

html5/js/lib/rencode.js
=> fix: do not convert u8a to string if it's already a string

html5/connect.html, html5/css/icon.css, html5/css/menu-skin.css, html5/index.html, html5/js/Client.js
TODO:
I could use some suggestions for a proper name for it other than "noVNC style menu".
=> noVNC-style vertical menu

html5/js/Client.js
Horizontal scrolling was flipped because the button codes were in the wrong order. The new behavior is now the same as the desktop client.
=> Set correct button codes for horizontal scrolling

html5/css/icon.css, html5/index.html, html5/js/Client.js, html5/js/Window.js
Pointer lock makes gaming over Xpra finally usable and actually works pretty well. When cursor lock is turned on, it automatically locks you to the focused window (which counts the desktop in desktop mode), and when you exit with with the `esc` key, it pauses, and waits for you to click on a new window to lock on. The paused mode (and cursor lock) is disabled by default and can be disabled through the float menu, with some colors to indicate.
The small bugfix is just using my new css classes to color the keyboard in as well, as the previous approach to coloring it wasn't working as jQuery cannot change css `:before` attributes.
=> Add gaming cursor mode (pointer lock) and a small bugfix

html5/js/Client.js
Sorry, but I screwed up e159d1c and mindlessly wrote .children() instead of just referencing the selector directly. This should fix it. Again, I am sorry
=> Fix the xdg menu bugfix that didn't do anything

html5/css/client.css
The session info box is not big enough to fit the text. This fixes that.
=> Fix session info box not being big enough

html5/css/client.css
Previously, the connecting UI used the browser's default font (which is often an ugly serif one). Change it to the font used everywhere else and replace one font usage to make them consistent everywhere.
=> fix: Don't use the default font for the connecting UI

html5/connect.html, html5/index.html
X-UA-Compatible is no longer necessary. The XHTML header is incorrect.
=> chore: Remove some legacy html parts

html5/js/MenuCustom.js
When the float menu is positioned in the bottom part of the screen, the dropdowns cannot be seen or interacted with. This solves that by making the menus open up or down depending on the position of the float menu. If the float menu is on the bottom half of the screen, it will open upwards, and vice versa.
=> Make the float menu list and window list open up or down depending on position

html5/js/Client.js
In desktop sessions, cursors only set when clicking on the screen, unlike seamless sessions where they work as intended and always are on screen. This fixes that.
=> Fix desktop sessions not setting cursors correctly

html5/js/Client.js
=> fix: Fix an issue where Modal focus was broken during minification

html5/js/lib/rencode.js
This isn't currently a problem, but breaks when using the code in a context that's using strict mode.
=> chore: Don't use implicit or conflicting vars in rencode

html5/css/client.css, html5/js/Client.js
When using shadow mode the window offset is incorrectly calculated causing the cursor position on the server to be off by quite a bit (depending on the XpraWindow's offset from the page's 0,0).
This is fixed by using the window div's position, instead of it's `.x` and `.y` fields
The next issue is that the cursor events are sent to the window even when the cursor isn't over the XpraWindow, this is fixed by checking if `win` is undefined while in shadow mode.
The final issue is that the drawn cursor image prevents events from propagating to the window, this is fixed by ignoring events on it.
=> Fix cursor glitching and offset when using shadow mode

html5/connect.html
Add the path to the xpra:// URL and the .xpra file. Also fix a bug where the URL was xpraws:// instead of xpra+ws:// (unless that was intentional in which case I can change it back).
=> feat: Support supplying path for desktop client launchers
